/// Flutter icons DeletAccount
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeletAccount
///      fonts:
///       - asset: fonts/DeletAccount.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DeletAccount {
  DeletAccount._();

  static const _kFontFam = 'DeletAccount';
  static const String? _kFontPkg = null;

  static const IconData delete_account_2x = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
